TOR/Contribution.md, TOR/PR_checklist.md
Draft of a Contribution.md file and a checklist for the TC
=> Contribution file, closes #5

Meetings/SG/20181106.adoc
Added the minutes of the 6th SG meeting on 2018/11/06.
=> Created 20181106.adoc

README.md
=> Add details about the EIP/bugfix process for contributors

Meetings/SG/20190305.md
Signed-off-by: MarcoMinghini <marco.minghini86@gmail.com>
=> Add minutes 10th SG meeting

Meetings/SG/20190409.md
=> Minutes of the 10th SG meeting

Meetings/SG/20190507.md
=> Add minutes 12th SG meeting

Meetings/SG/20190618.adoc
Signed-off-by: Jon Herrmann <herrmann@interactive-instruments.de>
=> Minutes of the 13th SG meeting 

Meetings/SG/20190718.md
=> Add minutes 14th SG meeting

Meetings/SG/20190903.md
=> minutes of the 15th SG meeting

Meetings/SG/20191008.md
=> Add minutes 16th SG meeting

Meetings/SG/20191112.md
=> minutes of the 17th SG meeting

Meetings/SG/20191217.md
=> Add minutes 18th SG meeting

Meetings/SG/20200121.md
Signed-off-by: Jon Herrmann herrmann@interactive-instruments.de
=> Add minutes 19th SG meeting

Meetings/SG/20200227.md
=> Add minutes 20th SG meeting

Meetings/SG/20200401.md
=> Draft minutes of the 21st SG meeting

Meetings/SG/20200507.md
=> Add minutes 22nd SG meeting

Meetings/SG/20200806.md
=> Add minutes 24th SG meeting

Meetings/SG/20200910.md
replaces #98 (expired certificate)
=> minutes of the 25th SG meeting

Meetings/SG/20201201.md
=> Add minutes 26th SG meeting

Meetings/SG/20201217.md
=> minutes of the 27th SG meeting

Meetings/SG/20210126.md
Add minutes of 28th SG meeting
=> Add minutes 28th SG meeting

Meetings/SG/20210223.md
=> add draft minutes of the 29th SG meeting

Meetings/SG/20210812.md
=> Add minutes 30th SG meeting

Meetings/SG/20220307.md
Add minutes of 32nd SG meeting
=> Add minutes 32nd SG meeting

Meetings/SG/20220419.md
@jonherrmann  @MarcoMinghini - please review and correct as necessary. Thanks.
=> add draft minutes of the 33rd SG meeting

Meetings/SG/20220525.md
=> Add minutes 34th SG meeting

Meetings/SG/20220805.md
=> Add minutes 36th SG meeting

Meetings/SG/20220921.md
=> Draft minutes, 37th SG meeting

Meetings/SG/20221018.md
=> Add minutes 38th SG meeting

Meetings/SG/20231113.md
=> Add minutes 40th SG meeting

Meetings/SG/20240311.md
Apologies, I thought I had published the pull request for the draft minutes already.
The repository changes have all been made directly after the meeting. With regard to the action regarding the JRC branches, it was not clear to me, to what extent this has been done (some of the repositories have branches others not).
=> add minutes (41st SG meeting)
